### ISSUE TITLE
IndexError: index 468 is out of bounds for axis 1 with size 468

### ISSUE THREAD

**Issue by newpokemon** [antonstagge/deepfashion-project#2]
Hello,

**Thank you for great work!**

I am a student learning ML. I am training on DeepFashion2 dataset, I followed all the steps in 'fashion.ipynb' and debug most of the errors surfaced. However, I am stuck at this error:

ERROR:root:Error processing image {'id': '012560', 'source': 'fashion', 'path': 'C:\\Project\\thesis\\big_deepfashion2\\train\\image\\012560.jpg', 'width': 468, 'height': 625, 'clothes': [{'category_id': 8, 'segmentations': [{'all_x_points': [-1.66, 104.4, 189.73, 228.68, 318.99, 392.73, 433.32, 469.78, 467.29, 467.29, 468.95, 468.12, 460.67, 444.1, 430.01, 405.98, 408.29, 427.52, 445.17, 455.18, 463.15, 466.47, 463.98, 459.01, 458.18, 456.52, 449.83, 442.83, 430.84, 414.27, 401.84, 394.38, 390.24, 373.67, 352.13, 340.53, 298.27, 244.42, 190.94, 177.42, 161.95, 154.94, 154.94, 161.56, 173.88, 192.22, 203.82, 218.73, 227.85, 228.68, 217.08, 140.02, 61.31, 33.97, 15.31, 1.17], 'all_y_points': [591.57, 579.15, 565.89, 564.23, 586.6, 617.26, 621.4, 621.4, 584.95, 512.86, 447.41, 412.61, 394.38, 345.5, 315.67, 260.16, 256.99, 251.05, 240.65, 224.08, 206.31, 197.19, 190.56, 187.25, 179.79, 174.82, 157.69, 138.57, 132.57, 97.77, 72.91, 38.94, 21.54, 14.09, 4.14, 2.49, 0.0, 0.0, 0.39, 4.03, 31.65, 53.85, 81.2, 120.97, 184.21, 242.76, 286.67, 329.76, 364.56, 404.33, 425.87, 453.21, 487.18, 507.89, 529.83, 541.83]}, {'all_x_points': [2.0, 6.0, 6.0, 1.0, 0.0, 0.0, 4.0, 7.0, 6.0, 5.0, 5.0, 2.0, -1.0, 1.0, 4.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 5.0, 29.0, 87.0, 107.0, 109.0, 147.0, 156.59, 153.07, 164.22, 168.0, 177.0, 186.0, 188.43, 181.0, 179.0, 180.0, 187.0, 196.0, 201.0, 206.0, 212.0, 217.0, 225.0, 231.0, 258.0, 227.0, 187.0, 101.0, 22.0], 'all_y_points': [534.0, 524.0, 512.0, 505.0, 473.0, 461.0, 456.0, 451.0, 443.0, 437.0, 437.0, 434.0, 423.0, 379.0, 317.0, 247.0, 147.0, 74.0, 58.0, 16.0, 3.0, 0.0, 1.0, 1.0, 1.0, 3.0, 30.0, 46.48, 75.0, 128.39, 151.0, 193.0, 221.0, 230.74, 229.0, 237.0, 248.0, 274.0, 298.0, 327.0, 356.0, 380.0, 392.0, 408.0, 426.0, 479.0, 498.0, 511.0, 544.0, 558.0]}], 'landmark': {'all_x_points': [0, 218, 1, 409, 335, 408, 442, 257, 233, 138, 253, 278, 0, 0], 'all_y_points': [0, 563, 591, 271, 42, 251, 137, 1, 421, 136, 226, 123, 0, 0], 'all_v_points': [0, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 0, 0]}}]}
Traceback (most recent call last):
  File "C:\Project\thesis\mrcnn\model.py", line 1805, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Project\thesis\mrcnn\model.py", line 1302, in load_image_gt
    mask, class_ids, landmark = dataset.load_mask(image_id)
  File "<ipython-input-4-4ab5e6ea5946>", line 101, in load_mask
    mask[rr, cc, clothing_idx] = 1
**IndexError: index 468 is out of bounds for axis 1 with size 468**

This is happening with multiple images with various indexes, so it is clearly not a problem with one specific data file. So far I have understood that it is a problem with the 'width' of these specific images, but I have no idea how should I solve this.

**Any help is greatly appreciated, thank you in advance.**  
: )

**Comment by sudarshan-ghuge** [comment]
As you can see in your code log, the width of your image is 468 but in your 'all_x_points' of your 'segmentations' array, one point is 468.95. This is triggering the 'list index out of range' error.

The solution that worked for me in a similar problem was to use [NumPy clipping](https://numpy.org/doc/stable/reference/generated/numpy.clip.html). Make sure all of the 'X-values' of the segment are less than or equal to the 'Width' of that image and all of the 'Y-values' of the segment are less than or equal to the 'Height' of that image.

Hope this helps.
